### ISSUE TITLE
Go SDK plan?

### ISSUE THREAD

**Issue by mshrwtnb** [box/sdks#1]
Hi, is there any plan to release the Go version of SDK?

**Comment by cbetta** [comment]
Hi @mshrwtnb, we currently have no immediate plans for a Go SDK, but we appreciate your feedback. Is there a specific project you have in mind that this would be used for?

We have an active [feedback forum available here](https://pulse.box.com/forums/909778-help-shape-the-future-of-box?category_id=330838) that we use to inform our roadmap. I'd recommend listing your request there.
